### ISSUE TITLE
Incorrect webhook verification

### ISSUE THREAD

**Issue by IvanMMM** [dark-dao/wallet-pay-sdk#1]
Depending on documentation, body request in webhook is an array, but your verification typings expect array element.
You can just edit typings and it will work as expected, just checked.

**Comment by dark-dao** [comment]
Thank you for your comment! Yes, this is my mistake. I will fix it

**Comment by dark-dao** [comment]
fix https://github.com/dark-dao/wallet-pay-sdk/commit/1b04df3b6de5e6fc73e3fdfc64793aa8a2dc209f

**Comment by dark-dao** [comment]
fix https://github.com/dark-dao/wallet-pay-sdk/commit/1b04df3b6de5e6fc73e3fdfc64793aa8a2dc209f
